name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Install Azure CLI
        uses: azure/cli@v1
        with:
          azcliversion: 'latest'
          inlineScript: |
            az --version

      - name: Autenticar no Azure com o token
        run: |
          az login --access-token ${{ secrets.AZURE_ACCESS_TOKEN }}

      - name: Deploy Infra com Bicep
        run: |
          az deployment sub create \
            --location eastus \
            --template-file ./infra/main.bicep \
            --parameters \
              vaults_vaults_azure_educadata_name="${{ secrets.VAULT_NAME }}" \
              workspaces_bricks_educadata_name="${{ secrets.DATABRICKS_WORKSPACE_NAME }}" \
              storage_account_name="${{ secrets.STORAGE_ACCOUNT_NAME }}"

      - name: Instalar Databricks CLI
        run: pip install databricks-cli

      - name: Importar notebooks para Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks workspace import_dir notebooks /Workspace/educadata --overwrite \
            --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN

      - name: Rodar testes com PyTest
        run: |
          pytest tests/
